spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/hsabati_autoecole
spring.datasource.username=Hisabaty_user
spring.datasource.password=Hisabaty_password
spring.jpa.hibernate.ddl-auto=update #create the tables in the database
spring.jpa.show-sql=true #show the SQL queries in the console
